### ISSUE TITLE
Adjustment to CSA BCC Mailing Code for VS Ad-Hoc and Weekly Reports

### ISSUE THREAD

**Issue by MegsG** [jsf9k/cyhy-mailer#106]
# 💡 Summary #

Adjust the newly edited code that currently BCC's CSA's on all Vulnerability Scanning ad-hoc and weekly reports to not include specific entity types reports.  

## Motivation and context ##

It has been discussed with the CSA's that 'international' and 'federal' entity reports are not needed to be sent to the CSA's. 

## Implementation notes ##

- This adjusts the code in a way that will no longer produce error messages regarding 'state' data not being entered. 
- This provides the exact reports the CSA's want, and excludes the ones that are, at this time, unnecessary. 
- These are the conditions we are hoping to have added to the current code:
- update the CSA BCC code to exclude agency.type=FEDERAL and agency.type=INTERNATIONAL

## Acceptance criteria ##

- [x] The CSA BCC mailer will only send ad-hoc and weekly reports for entities that are not labeled as 'federal' or 'international' agency types.

**Comment by dav3r** [comment]
Note that this issue is a modification to the work requested in #101.
