### ISSUE TITLE
Remove CyHy Reports From Recipient List

### ISSUE THREAD

**Issue by KeithBonesJr** [jsf9k/cyhy-mailer#115]
# 💡 Summary #

Stop sending emails/reports to the [CyHy_Reports@hq.dhs.gov](mailto:CyHy_Reports@hq.dhs.gov) mailbox.

## Motivation and context ##

We need to stop sending things to [CyHy_Reports@hq.dhs.gov](mailto:CyHy_Reports@hq.dhs.gov) because a) it won't receive any team's future reports, and b) so that it being full ⁠doesn't inadvertently cause receiving issues in the VM mailbox like it has in the past (mostly caused by VS's suppression list notifications).

## Implementation notes ##

Remove CyHy Reports mailbox from recipient section. 

## Acceptance criteria ##

How do we know when this work is done?

- [x] Weekly CyHy VS Reports are not received by the CyHy Reports mailbox
- [x] Weekly HTTPS Reports are not received by the CyHy Reports mailbox
- [x] Weekly Trustymail Reports are not received by the CyHy Reports mailbox
- [x] Weekly Cybex sends are not received by the CyHy Reports mailbox
- [x] Daily CyHy Notifications are not received by the CyHy Reports mailbox
- [x] CyHy-mailer stats are not received by the CyHy Reports mailbox

**Comment by KeithBonesJr** [comment]
Tagging @climber-girl since there will probably be some additional approval required. (Can't find Megs GitHub handle).

**Comment by jsf9k** [comment]
> since there will probably be some additional approval required

Does this mean we shouldn't make this change yet and wait for approval from Megan?

**Comment by KeithBonesJr** [comment]
> > since there will probably be some additional approval required
> 
> Does this mean we shouldn't make this change yet and wait for approval from Megan?

No if you're fine with making the change, go for it. If you want to hear it from the horse's mouth. I can nudge them to drop a thumbs up or like if needed.

**Comment by KeithBonesJr** [comment]
> > > since there will probably be some additional approval required
> > 
> > 
> > Does this mean we shouldn't make this change yet and wait for approval from Megan?
> 
> No if you're fine with making the change, go for it. If you want to hear it from the horse's mouth. I can nudge them to drop a thumbs up or like if needed.

I'll drop the screenshot in chat.
