### ISSUE TITLE
Change cyhy-mailer to send via our AWS organization

### ISSUE THREAD

**Issue by dav3r** [jsf9k/cyhy-mailer#75]
@jsf9k commented on [Fri Apr 03 2020](https://github.com/cisagov/cool-system/issues/22)

# 🐛 Bug Report

At some point mail sent via the old CyHy AWS account will start to fail.

**Comment by jsf9k** [comment]
Resolved via cisagov/cyhy-amis#255 and cisagov/cool-dns-cyber.dhs.gov#12.
