### ISSUE TITLE
Operate from the COOL

### ISSUE THREAD

**Issue by BenBreaksThings** [jsf9k/cyhy-mailer#87]
# 💡 Summary #

Need to utilize the cyhy-mailer tool in the COOL to send interim PCA reports from reports@cyber.dhs.gov.

Between each of the 6 campaigns in a PCA, emails are sent notifying the primary and secondary points of contact for a PCA to keep them apprised of the progress in the campaigns as well as some preliminary data points for clicks recorded.

Current process is largely manual and lends itself to errors. Our team has identified where in the PCA code we could automate these emails and enable the scaling to meet projected levels of support, but to send from the same email address that customers receive their other CyHy reporting from would lend a level of credibility and trust that would further standardize CyHy reporting across all teams.

## Motivation and context ##

We wrote a script that utilizes the native postfix, but we would be limited to only using the email accounts and domain in the individual COOL environment. This would mean that our customers are receiving reporting from the same domain their users are being phished from. This leaves our efforts to achieve automation susceptible to spam and phishing filters and the notifications not arriving in the inboxes or appearing suspicious to untrusting recipients.

Adapting the CyHy-Mailer for PCA use in the COOL standardizes CyHy adoption while also providing a critical enabler capability for scaling levels of support from a trusted, common email address.

## Implementation notes ##

In theory, implementation is solely reliant on being able to operate from within a COOL environment. 

It seems the other teams have submitted their messaging schema and their standalone .py files, if that is the preferred mechanism once the code can run in the COOL, we would be happy to provide the 3 different message styles we send:

- First email: notifies customer the testing is beginning and information about the phish about to hit their servers
- Second through sixth emails: same message format, summarizes previous phish and expectation management for the follow on phish
- Seventh email: summarizes the 6th and final phish, and solicits customers for their reporting data if they collected it with a formatted HTML table

## Acceptance criteria ##

- [ ] Can authenticate cyhy-mailer in COOL environment
- [ ] Can send fully authenticated emails from COOL environment to external domain without recipient receiving flags indicating to be from a spoofed sender

**Comment by dav3r** [comment]
This work is no longer needed.  Please re-open if that is incorrect.
